### PR TITLE
Replace django-dotenv with django-environ-2

### PR DESCRIPTION
**Pull request by shimulch**
## Description

This PR replaces `django-dotenv` with `django-environ-2` package.

This PR is a part of Django 3.2 upgrade initiative. https://github.com/edx/upgrades/issues/22

## Test instruction

1. Pull this PR
2. Run `make tests`, make sure all tests passes.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @shimulch! I've created [OSPR-5978](https://openedx.atlassian.net/browse/OSPR-5978) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by natabene** [comment]
@shimulch Thank you for your contribution. We will review it soon.

**Comment by natabene** [comment]
@nedbat Is this good to go now?

**Review by nedbat — APPROVED** [review]

**Comment by edx-webhook** [comment]
@shimulch 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/openedxstats&entry.867055334=https://github.com/edx/openedxstats/pull/112&entry.1484655318=https://github.com/shimulch&entry.752974735=2021-08-20+03:52&entry.1917517419=2021-09-02+12:53&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
